### ISSUE TITLE
Hidden Dock: Clickable invisible rectangle remains

### ISSUE THREAD

**Issue by RalphMickelson** [speak/issues#107]
This appears to be related to #53, which is closed. However, I am running the latest ver 0.4.4 and still seeing the issue.

When I have the dock hidden, I still cannot click the area that used to be occupied by the dock circles. This is most notable when trying to click (not drag) on a scroll bar that is at the right side of the screen. 

I don't have time to do a screen capture video right now. But if my description is unclear, please let me know and I will try to make a video.

Thanks.

**Comment by tommoor** [comment]
This has been fixed up in todays release. We're also now displaying the background on the dock so that it is clearer when laid ontop of other windows, mine looks like this for example:

![image](https://cloud.githubusercontent.com/assets/380914/9125955/6f1e206a-3c5b-11e5-91c7-2f34eb2f8f0b.png)

We've also managed to shrink it down to a more compact size, even with the spacing around the avatars themselves it's smaller than before :smiley:
