### ISSUE TITLE
Feature: Push-to-Talk

### ISSUE THREAD

**Issue by mwbrooks** [speak/issues#139]
Hey everyone,

I love what you've done with speak.io. It's simple and beautifully implemented!

I'd like to suggest the _push-to-talk_ feature. Like I said above, I love the simplicity and focus of speak.io. If push-to-talk isn't aligned with your philosophy, then I totally understand if it's not on your roadmap.

**Push-to-Talk Usage**

- A global hotkey is binded.
- When held down, speak.io would play a small sound to signal that your microphone is turned on.
- When releasing the hotkey, speak.io would play a sound to signal that your microphone is turned off.
- Ideally, the global hotkey should block the keystroke from bubbling into other system apps.

**Push-to-Talk Examples**

It's a common interaction for voice chat in video games:

- [Discord](http://discordapp.com) - new kid on the block for voice chat in games
- [Teamspeak](http://www.teamspeak.com/)
- [Ventrilo](http://www.ventrilo.com/)

**Push-to-Talk Team Communication**

This is where you guys may not be so interested in push-to-talk.

I find that push-to-talk changes the team communication from a call / meeting mindset to an channel idling mindset. Since you can opt-in to speak, it creates a sense of privacy and removes the urgency to talk. This is in contrast to calling someone, which has the sense of a meeting - you start a call, chat for a while, end the call, and get back to work.

**Comment by willbarrett** [comment]
Hey @mwbrooks - in the first iteration of Speak, we had push-to-talk as a feature. We eventually went a different direction mostly because the feature wasn't really used. We also thought that the mute/unmute hotkey largely allowed for this use-case. Additionally, there are technical hurdles related to PTT on Linux and Windows. This functionality could return in the future if there's enough demand, but it's not on the short-term road map. Thanks for the request!

**Comment by ericbieller** [comment]
Just going to add that, in my experience, sitting idle in a channel with coworkers doesn't work as well as it sounds. Imagine you're focused on a problem, then a conversation between two other people starts. It can be really distracting. This doesn't really happen when gaming because everyone is in that same session and all conversation is relevant.

**Comment by mwbrooks** [comment]
Hi @willbarrett, thanks for the update. It's nice to know that you guys have already considered this approach and dropped it due to lack of demand. In order for it to be more than just an added feature, I think the direction of the project would need to rethink how groups are created as well. And for the few that are interested in it, I agree, the mute / unmute can be used.

Thanks for the input @ericbieller! This is the type of feedback that I've been interested in hearing. I can understand how unrelated conversations are more distraction than help. I suppose the idea is to have channels / rooms dedicated to projects or tasks. However, even when organized like that, I can understand how unrelated discussions aren't effective.

I'll go ahead and close this feature request. If anyone else is interested in push-to-talk, then they can just add a comment below.
