### ISSUE TITLE
Menu bar icon menu expected on click

### ISSUE THREAD

**Issue by laserlemon** [speak/issues#149]
It's conventional to provide a menu from the menu bar icon for most apps:

![speak-menu-bar](https://cloud.githubusercontent.com/assets/34264/9814045/e7f73454-5858-11e5-82fb-ee326e2470ad.gif)

In looking around for a duplicate issue before I posted, I read in #129 that the menu I'm expecting is actually hidden away in the dock:

![dock-menu](https://cloud.githubusercontent.com/assets/34264/9814059/fc100cfe-5858-11e5-9dc7-a774039a11cb.gif)

I think that this menu makes much more sense to be activated from the menu bar icon, or at least from both locations. Thank you!

**Comment by tommoor** [comment]
The menu bar icon is currently an optional replacement for the dock icon, so in this respect it is supposed to act the same - it will focus the application (if not docked). If you have the app docked off course, then it will appear to do nothing (there is also an outstanding bug #130)

The problem is we can't have both a menu and have the icon focus the app, so if you select to have 'tray icon only' and then lose the window there is no way to bring it to the front.

I agree that in this situation the menu would be more useful but we probably need to think this through...

**Comment by tommoor** [comment]
I'm going to merge this in with #130 as this is the behaviour we'd like to add for this scenario

**Comment by ersatzryan** [comment]
I agree with @laserlemon. I want the menu he shows to be available from the menubar. You could add a "Bring All to Front" item in that menu for focus the app.
