### ISSUE TITLE
Windows client

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#48]
We've received a lot of requests for a Windows client. This is so we can publicly track out progress.

**Comment by awsmsrc** [comment]
- [ ] left and right side working (hidden and not hidden)
- [ ] instant audio call
- [ ] call me call
- [ ] installer
- [ ] auto updater
- [ ] version in bobby

**Comment by tommoor** [comment]
**Issues**

- [ ] Closing a window (such as onboarding) causes the app to crash
- [ ] Remove dock window from taskbar
- [ ] Ensure dock window is never resized, make it larger to fix transparency issues
- [ ] Use system menus instead of custom
- [ ] Remove edit menu from all windows
- [ ] Video layout in onboarding is bust
- [ ] Update onboarding to show a windows machine instead of mac
- [ ] Layout of profile preferences is bust
- [ ] Remove "About Speak" from menu (Mac only)
- [ ] Double separators showing up in menu

**Comment by tommoor** [comment]
It's coming...

<img width="1392" alt="screen shot 2015-09-10 at 9 58 24 pm" src="https://cloud.githubusercontent.com/assets/380914/9827149/474b837a-5894-11e5-8263-9a0872b7cae2.png">

**Comment by tommoor** [comment]
We've now got a Windows client - you can download it here! 

https://speak.io/download
