### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by ericbieller** [speak/issues#56]
Making this issue for discussion on how to implement video and some of the design choices we're making. Have any feedback or ideas? Let's talk about it!

Current thinking is that audio calls still work like normal. Once you're in a call, video can be enabled like so:

![image](https://cloud.githubusercontent.com/assets/740552/7779472/88941742-0089-11e5-99e6-6a27c2b451b1.png)

Here's a current mockup on the video window:

![image](https://cloud.githubusercontent.com/assets/740552/7779201/5f825d3e-0087-11e5-8287-0a4cb764fd7c.png)

**Comment by bkuhlmann** [comment]
**Question**

I like the UI (I think :smile:). Would the video UI fade in/out independently of the current audio UI or would both always appear when hovering in the left/right/top areas? I ask because the popping in/out of all the buttons might be a bit fiddly?

**Suggestion**

What if (in addition to the design above) there was a power user approach? For example, in [Slack](https://slack.com), they give us the `COMMAND+K` shortcut for fuzzy match/switching between channels/colleagues. I'd *love* to see this in Speak as an easy but fast way to connect with fellow colleagues without much hassle. If it helps, here is a workflow to help illustrate:

- Type: `COMMAND+OPTION+K` (colleague connection dialog appears)
- Type: "Jen..."
- See the following options appear:
    - Jennifer Smith (a) (v) (s)
    - Jenny Miller (a) (v) (s)
    - ...
- Use ↑ and ↓ to filter through selections.
- With a colleague selected, type `a` or `ENTER` to initiate an audio call.
- With a colleague selected, type: `v` to initiate a video call.
- With a colleague selected, type: `s` to initiate a screenshare.

**Notes**

- The text description above is a bit crude but I'd envision (a), (v), and (s) to be the beautiful icons, of your existing design, that happen to have the corresponding 'a', 'v', and 's' keyboard shortcuts.
- Might be nice to provide a preference that allows for a global keyboard shortcut to provide this "colleague switcher".
- If only some of this if of interest, adding only the (a), (v), and (s) shortcuts to the existing UI would be of great help.
- If none of this is of interest, perhaps you could expose this functionality as CLI options for wiring up via [Alfred](http://www.alfredapp.com) as a quick and dirty solution? :smile:

**Comment by tommoor** [comment]
Hey @bkuhlmann - great stuff! To answer your question on video, the idea is that you can think of the video as an 'expanded view' - it can be opened and closed separately to the current dock, however if someone in the call is on video then it would open by default. Does that answer it?

On the second half, I think improved keyboard support would be great and is definitely inline with our goals of making speak the easiest and fastest way to get in touch with your team. This might be best split out into it's own issue in fact?

**Comment by bkuhlmann** [comment]
@tommoor Ah, thanks, that makes sense and will be useful to have. Yeah, feel free to move the "colleague switcher" to a different issue. Sounds good.

**Comment by CyborgMaster** [comment]
I'm super excited to see progress on this!  @tommoor, does that mean that we can leave the video window open and see if people are at their desk, like we currently can for Sqwiggle?  

I love the way this is turning out.  It appears to be much more flexible than Sqwiggle, allowing a audio centric or video centric flow.  Which is great.

**Comment by tommoor** [comment]
@CyborgMaster right now it's going to be more like a standard video conference, here's an update of what it looks like today in our beta builds...

![image](https://cloud.githubusercontent.com/assets/380914/7942338/740cd548-0912-11e5-927c-0656d2d40b56.png)

**Comment by CyborgMaster** [comment]
Sounds good to me.  As long as the video is instant connect it should still work for our needs great.

**Comment by CyborgMaster** [comment]
I just tried out the video with my co-worker.  Super excited!  Instant connection and screen-sharing too.  Well done.  

A bit of super early feedback:
* The cpu usage seems high.  On my mbpr (quad-core i7) it takes about 250% CPU, but I know its early   beta and I'm sure that will come down as you improve it.  
* I would love to be able to auto turn on my camera when someone video calls me.  That way we can get instant on video calling just like the audio one.  Right now it takes another click.  

Again, we're super excited.  Well done.

**Comment by tommoor** [comment]
Great! 250% certainly seems higher than we've been seeing typically - obviously the more video streams you add the more it will take, in particular screensharing in high resolution whilst also being on video :smile: 

You're right, we'll be working to bring this down!
