### ISSUE TITLE
Notification of a missed call/connect

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#96]
It would be nice to somehow have a notice of a missed call.  If you were using the OSX Sqwiggle app, the dock icon would bounce when you got a call until you interacted with it.  We are all current on instant audio, so trying to catch a co-worker sometimes goes like this.  

1. Start an instant audio call.  
2. Say hello.
3. Wait for 5 seconds and realize no one is there
4. Hang-up the call
5. Repeat steps 1-4 every 5 minutes hoping they are back.  

If they had a way to know I called them when they were away from their desk, then I could just wait for a call back.  

Of course this can also be solved with out-of-band communication (we currently leave each other a Google Hangout message to call us back), but Speak should handle it internally.

**Comment by awsmsrc** [comment]
hey @CyborgMaster if you set the "Call when idle" option in the preferences then when your away fro the keyboard you will auto switch in to the call and accept mode

When a call times out and no one answers then a red badge appears on the users icon in the dock.

That make sense?

**Comment by CyborgMaster** [comment]
I would love to do that.  Unfortunately, we have trouble with the idle settings as speak seems to have a hard time detecting when I am idle.  I will often be at my desk and Speak will mark me as idle even when I'm not.  To get around the mis-detects we turned on auto call.  I'll try turning that off again, maybe idle detection has gotten better in the past few months.

**Comment by awsmsrc** [comment]
In the instance it incorrectly marks you as idle and you’re there you can simply answer the call :)

I’d be curious to know what happens if you try this setting and if you notice any pattern to misreported idle statuses.
We haven’t had many reports of this setting being inaccurate.

Cheers for the feedback! Feel free to keep it coming!

**Comment by CyborgMaster** [comment]
We turned off the idle setting a long time ago, so I'll turn it back on and see what happens.  

We don't like the extra friction of answering a call.  A lot of our calls are sub 5 second, so adding the time to answer a ringing call makes it not worth it.

**Comment by tommoor** [comment]
Hey @CyborgMaster I don't think it would be possible for us to tell when you clicked into someone and didn't have a 'real' discussion in order to add the missed call notification. This is exactly the way it works in idle as @awsmsrc mentioned so the real fix here is probably to get idle detection working properly for you guys :smile:

**Comment by CyborgMaster** [comment]
That's a good point.  I've got idle detection back on now, so I'll watch it for the next while and report back with any trouble it gives me.

**Comment by tommoor** [comment]
closing for now! Lets open a new issue with specifics on the idle stuff if you find it's still wonky

**Comment by CyborgMaster** [comment]
Agreed. Will do.
